### PR TITLE
Resize font when props updated

### PR DESCRIPTION
**Pull request by cedmax**
this PR is meant to solve this issue => https://github.com/gianu/react-fittext/issues/19

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Thank you for your PR. I have manually included your commit on master, because the PR included cosmetic changes.

**Comment by cedmax** [comment]
Hi @denis-sokolov, thanks. 
The cosmetic changes were meant to make the script consistant: right now thre's a mix of single and double quotes and mixed usage of new lines between methods definition. 
I know it was kind of out of scope in this PR, but I thought it was an improvement. 
I'm sorry if it shouldn't have been there

**Comment by denis-sokolov** [comment]
I agree with the value of cleanliness, but it did distract from the meat of the PR.

**Comment by cedmax** [comment]
sure, no problem at all :)

**Pull request closed without merging**
